version: '3.7'

services:
  frontend:
    container_name: frontend
    image: frontend_img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - atommuse-network

  json-server:
    container_name: json-server
    image: jsonserver_img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    command: npm run backend
    networks:
      - atommuse-network

networks:
  atommuse-network:
    driver: bridge