version: '3.7'

services:
  frontend:
    container_name: frontend
    image: frontend_img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - atommuse-network
    environment:
      - COMPOSE_DOCKER_CLI_BUILD=0

networks:
  atommuse-network:
    driver: bridge