name: Notify Discord on Push
on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Notify Discord
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Code has been pushed to the repository!"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
